### PR TITLE
Release/91

### PR DESCRIPTION
**Pull request by dbolser-ebi**
This will merge against release/91 (which I'm currently running), but not master. I'm pushing it against master as it seems like the right thing to do to make sure the changes are kept long term. Seems there is a conflict? I would resolve this, but my pipeline is currently running, and I don't know how to do it safely!

Cheers,
Dan.

### CODE REVIEW

**Comment by mn1** [comment]
I made a major update yesterday to master.

No worries, I'll have a look at this.

**Comment by dbolser-ebi** [comment]
Urg... bad timing... Shall I push to 91 in the mean time?

**Comment by mn1** [comment]
Sure, you can do that. 

But leave this pull request open, because ultimately your changes have to end up on master.

**Comment by mn1** [comment]
Done:
https://github.com/Ensembl/ensembl-funcgen/pull/18

**Pull request closed without merging**
